version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
      typescript-eslint:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"
      playwright:
        patterns:
          - "@playwright/*"
          - "playwright*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vite-plugin-*"
